// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: proto/request.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppendService_Append_FullMethodName = "/internal.generated.AppendService/Append"
)

// AppendServiceClient is the client API for AppendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppendServiceClient interface {
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
}

type appendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAppendServiceClient(cc grpc.ClientConnInterface) AppendServiceClient {
	return &appendServiceClient{cc}
}

func (c *appendServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, AppendService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppendServiceServer is the server API for AppendService service.
// All implementations must embed UnimplementedAppendServiceServer
// for forward compatibility.
type AppendServiceServer interface {
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	mustEmbedUnimplementedAppendServiceServer()
}

// UnimplementedAppendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppendServiceServer struct{}

func (UnimplementedAppendServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedAppendServiceServer) mustEmbedUnimplementedAppendServiceServer() {}
func (UnimplementedAppendServiceServer) testEmbeddedByValue()                       {}

// UnsafeAppendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppendServiceServer will
// result in compilation errors.
type UnsafeAppendServiceServer interface {
	mustEmbedUnimplementedAppendServiceServer()
}

func RegisterAppendServiceServer(s grpc.ServiceRegistrar, srv AppendServiceServer) {
	// If the following call panics, it indicates UnimplementedAppendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppendService_ServiceDesc, srv)
}

func _AppendService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppendServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppendService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppendServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppendService_ServiceDesc is the grpc.ServiceDesc for AppendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internal.generated.AppendService",
	HandlerType: (*AppendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Append",
			Handler:    _AppendService_Append_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/request.proto",
}
